### ISSUE TITLE
Save corruption in the Red Forest

### ISSUE THREAD

**Issue by seaz5150** [Decane/SRP#137]
Any save made after entering the Red Forest will get corrupted (Yantar save file in the attached archive). 

Log when loading the corrupted save (varies, the log will probably not tell you much, it's just the save file getting corrupted in various ways I believe):

```

! [LUA][ERROR] Abort(): [_G.set_save_marker]: Save marker mismatch '_WeatherManager' 0 ~= 5.
 
FATAL ERROR
 
[error]Expression    : fatal error
[error]Function      : CScriptEngine::lua_error
[error]File          : E:\priquel\sources\engine\xrServerEntities\script_engine.cpp
[error]Line          : 180
[error]Description   : <no expression>
[error]Arguments     : LUA error: ...\common\stalker clear sky\gamedata\scripts\_g.script:456: [_G.set_save_marker]: Save marker mismatch '_WeatherManager' 0 ~= 5.
 

stack trace:
```

[save.zip](https://github.com/Decane/SRP/files/7111314/save.zip)

**Comment by Decane** [comment]
I can't reproduce the reported issue. I loaded your save, made a beeline for the Red Forest, made a save at the entrance, and loaded it just fine. I tried with both [v1.1.3](https://github.com/Decane/SRP/commits/v1.1.3) and the [current tip of the master branch](https://github.com/Decane/SRP/commit/545ff2d6bcd6939eeb6ea85e9de676f4d87b7321).

The error message you quoted implies that the amount of saved weather data loaded by the game doesn't match the amount saved. Is it possible that the saves you are trying to load were made with a version of the SRP that includes commit [Fixed save persistence of in-game weather](https://github.com/Decane/SRP/commit/0a7f5db00c3e1e21b2ce1b70b1afb2b8834419b8), and that you have since reverted to an earlier version of the SRP, e.g. v1.1.3? If so, that's the root cause of your crash; versions of the SRP predating the aforementioned commit cannot be used to load saves created with that commit in place.

I suggest you delete/rename your current SRP 'gamedata' folder and instead install the latest master branch version. Then try to load your Red Forest saves. Do they work?

**Comment by seaz5150** [comment]
I tried using the version from the repo and it did not help.

The error messages change every time to something entirely different, as it would with corrupted saves.

All I did previously was download v1.1.3 from ModDB, select some optional files from the archive and add the czech localization file. I tried reverting back to the english one, but that did not help either. I have not touched the files other than that.

I don't really plan on finishing the playthrough anymore anyway, so you don't have to worry about fixing my game if it works for you.
