### ISSUE TITLE
Clear Sky crashing on startup (Retail version)

### ISSUE THREAD

**Issue by Heater6123** [Decane/SRP#141]
After adding the Game data folder to the root directory of CS my game won´t start anymore (without SRP it runs normally).
The Error I receive:
xrEngine.exe caused BREAKPOINT in module "C:\Program Files (x86)\Deep Silver\S.T.A.L.K.E.R. - Clear Sky\bin\xrCore.dll" at 0023:00C1BA94, xrDebug::backend()+164 byte(s)

The xray log:

* Detected CPU: GenuineIntel P3 family, F6/M14/S3, 2710.00 mhz, 22-clk 'rdtsc'
* CPU Features: RDTSC, MMX, SSE, SSE2

Initializing File System...
using fs-ltx fsgame.ltx
FS: 26203 files cached 28 archives, 4848Kb memory used.
Init FileSystem 0.829408 sec
'xrCore' build 3464, Jul 29 2008

 
FATAL ERROR
 
[error]Expression    : fatal error
[error]Function      : CInifile::r_section
[error]File          : E:\priquel\sources\gold\xrCore\Xr_ini.cpp
[error]Line          : 443
[error]Description   : <no expression>
[error]Arguments     : Can't open section 'zero_immunities'

I´d appreciate any help I can get to fix this, so far i tried to un and reinstall CS, download the SRP again but nothing is working.

**Comment by Decane** [comment]
Is your game patched to v1.5.10?

**Comment by SurDno** [comment]
Okay, yeah, sorry for going off-topic, but a little bit more research and it turns out you do indeed have a build which is not really publicly available.

It appears that you have a CD drive of the game with a version that was sold in Poland (and possibly somewhere else?). Even if the patch number has not changed, it was built 8 days later than initial release and it's something that may possibly shed the light on a serious part of the game development history.

If you don't mind, can you tell me the following details:
- What's the version of the game in the main menu screen?
- Do you have 'patches' directory in you game folder?
- If yes, which files do you have in it?

And if it's possible in any way, I'd really appreciate if you upload your freshly installed copy of the game somewhere on the internet. This is will mean a lot for me the development history research in general.

Thanks!

**Comment by Heater6123** [comment]
Hey, yeah sorry, i misread 1.5.01 as 1.5.1.
I do have patches in the game folder and it contains xpatch_01.db but nothing else.
Also i bought the game in Austria if thats interesting.

**Comment by SurDno** [comment]
Yes, 1.5.01 is indeed the version unavailable to both Eastern Europe and Western public. And xrpatch_01.db is in none of the other official installations

All this time Austria had a lost patch, and we were none the wiser. Most people update the game without looking, I guess.

I will be waiting for your upload. Thanks again, this really means a lot.

**Comment by Heater6123** [comment]
Here is the link for the drive folder: https://drive.google.com/drive/folders/1N-RNcZ7N36uoXkam3DRri4Qpl0ZSp08d?usp=sharing
Also after updating to 1.5.10 the game starts up again, thank you :D
