### ISSUE TITLE
Hunger Restoration

### ISSUE THREAD

**Issue by vertebralis** [Decane/SRP#147]
it was intented that Scar supposed to have hunger but it was cut or mistake was made and it wasnt fixed even in latest patch. There is no lore or explanation in the story about his ability to be satieted all the time. I think its should be fixed because other stalker's have satiety level.

**Comment by SurDno** [comment]
> it was intented that Scar supposed to have hunger

When was it intended? There is no design document, prerelease build or any other internal piece of information to suggest that it was ever planned to return, let alone being cut.

> I think its should be fixed because other stalker's have satiety level.
I suppose you mean other games in the series, since NPCs aren't affected by hunger at all and the only times they eat it's just an animation. Still, that's not 
Nevertheless, there is no reason to suggest this was unintentional.

**Comment by vertebralis** [comment]
Yes,i meant in other stalker games. But still at least it would be good to
have compatible SRP addon since there was no sleeping bags, real weapon
names, sweetfx, restored ironsights either in game or design documents. I
would be cool to have this feature to match other stalker game. If it was
at least explained story-wisely why Scar doesn't have hunger i could
understand. But he's just unique without any explanations. He differs from
other main characters.

нд, 9 жовт. 2022, 04:24 користувач SurDno ***@***.***> пише:

**Comment by SurDno** [comment]
> it was intented that Scar supposed to have hunger but it was cut 

When was it intended? There is no design document, prerelease build or any other internal piece of information (such as recent internal bugtracker leak) to suggest that it was ever planned to return, let alone cut at some point.

Clear Sky interface lacks a separate icon for hunger among its indicators on the right. The only one in the resources is the one left from SoC. 

>  or mistake was made 

How can it possibly be a mistake that someone intentionally changes a meaningful value of character's stats to zero?

> There is no lore or explanation in the story about his ability to be satieted all the time.

Beanpolev mentions that Scar's endurance was improved after the Great Emission, and it supplied his body with energy. If you like it, you may take it as an official in-game explanation, even though that's a huge stretch.

But even if those are unrelated, there does not really have to be an explanation for a gameplay element (or lack of it, in our case). There is no explanation why Scar's PDA can transcribe almost all audio messages, Marked One's can do that with some of them and Deg's can't do that at all. There is no explanation why Scar and Marked One can't sleep (on their own accord, anyway). There is no explanation why bandits feel differently to Scar as a freedomer than to all the other freedomers. 

Those just exist.

> because other stalker's have satiety level.

I suppose you mean other games in the series, since NPCs aren't affected by hunger at all and even when they do eat, it's merely an animation which serves no gameplay purpose.

Still, that's not unusual. There are many things that were removed during the development of CS but brought back during the development of CoP. Take 9x39 SP-5 or bloodsuckers being attackable while in camouflage mode, for example. Should those be added to CS for the sake of consistency as well? 

>  and it wasnt fixed even in latest patch
>  I think its should be fixed 

While we can't know for sure why it was done, there is no reason to suggest that hunger's removal was unintentional, so there's objectively nothing to "fix", unless you claim every change to your liking as a fix. 

It is possible that this was done out of devs' decision to simplify the game. While today, in the era of Anomaly's item bloat and useless crafting mechanics, we are used to abundance of gameplay elements, it is suggested that this was not the case during the development of Clear Sky. Complex stats of artifacts from SoC have been changed to basic "radiation in, radiation out" because devs previously received feedback about the original game's implementation being too confusing, so this might be a case here.

**Comment by vertebralis** [comment]
I hope Stalker 2 will tell us more about Scar)

нд, 9 жовт. 2022, 04:42 користувач SurDno ***@***.***> пише:

**Comment by SurDno** [comment]
@Decane getting back to you with a bit more in-depth research about hunger.

First of all, we know that its removal is intentional according to a quote by Andriy Verpahovsky, lead CS game designer:

> It’s a decision "from above" that the players don’t like hunger. We decided not to bother and not remove the gameplay element properly, just set it to zero. In truth, it was someone's personal issues with resource management. Even if those resources are in-game canned food.

It's true that the hunger was never properly removed from the game - the engine code is the same as in SoC, which does the following:

- Decreases satiety by the value of `satiety_v` each second, leaving it within the bounds of 0 and 1.
- If the satiety is > 0, add `satiety_health_v` to player's health each second, effectively giving passive regen. If satiety is less or equals 0, take `satiety_health_v` from player's health each second. Neither of that (neither regen, nor damage) affects you if you're currently bleeding (though this behaviour is likely unintentional, as the comment above it says: "satiety gives health when there are no open wounds").
- Add `satiety_power_v` to player's energy level every second, no matter what their current satiety is (also seems to be wrong, as CoP later changed this code to give a fraction of `satiety_power_v` that equals the current satiety percentage of the player).

Not only the engine code but the configuration files have the same values for all satiety-related variables as well. Then why is it not working in the game? 

It actually is, despite there being no indication of player's current satiety in in-game HUD.

The element that is not present in SoC but is present in CS is the following line in actor.ltx:
```health_restore_v        = 0.0003```
which gives the player a passive regen of 0.03% health per second. The hunger actually still affects Scar's health, but as it only takes 0.01% health per second, your passive regen always nullifies that, so you never get any visible damage. This also means that hunger does affect your passive regen, as you effectively get 0.04% when not hungry (0.03% default regen + 0.01% satiety-based regen) and 0.02% when hungry (0.03% default regen - 0.01% satiety-based regen).

I am not sure what the preferred course of action would be for SRP - whether it is to remove leftover effects of hunger or bring back current satiety indication. Just wanted to let you know since I was wrong about hunger being set to 0 in in-game configuration files.

BTW: `satiety_critical` is not used by the engine. You can remove that line from actor.ltx.

**Comment by Decane** [comment]
So hunger is still present in CS and even has an in-game effect, it just lacks an indicator on the HUD - interesting, nice detective work. :)

>I am not sure what the preferred course of action would be for SRP

Suppose the indicator is re-enabled and the player reaches maximum hunger. They probably won't even notice the health restoration rate reduction (a slower increase over time is much less noticeable than a reduction over time as in SoC), and might be confused why there is a hunger indicator at all when hunger seems to carry no discernible penalty.
