### ISSUE TITLE
Strange floating bug

### ISSUE THREAD

**Issue by litvyakov1488** [Decane/SRP#15]
After the battle for the bridge to Limansk I quicksaved as usual. So, whenever I load this quicksave my character as if fired out of canon floats real fast out of map into the sky. That's pretty sad cuz I spent an hour or two in the Red Forest shooting, gathering, completing quests, etc (and finally the bridge battle of course) and there is no other savefile I possess.
[uriel_quicksave.zip](https://github.com/Decane/SRP/files/1896340/uriel_quicksave.zip)

**Comment by SurDno** [comment]
That happens pretty often when two dynamic objects try to interact with each other: corpses, bolts, items, grenades, etc. I had my player flying away from Cordon in SoC five times or so.

I guess you've made this save directly on the bridge, yep? Because it's the only dynamic object I can think of.

Since that bug lies very deep in the game engine code, it's not fixable for now.

**Comment by Decane** [comment]
@litvyakov1488 Physics glitches are, unfortunately, beyond the scope of the SRP to fix, as SurDno suggested. But don't worry, all is not lost. Open `gamedata\configs\creatures\actor.ltx` and find parameter `ph_mass`. Temporarily change its value from "80" to "800000". That should allow you to load your savegame without propelling you off the map.

I suggest undoing this change once you've made another save somewhere you're not glitching into the Red Forest bridge, as making Scar weigh 800 tonnes is likely to introduce other physics glitches.

**Comment by litvyakov1488** [comment]
Ok, thanks. I’ll try it tomorrow
