### ISSUE TITLE
'Defend the Patrol: Bus Stop' quest not starting exclusively in SRP

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#21]
When playing vanilla game, as you make your way towards the Underpass you here a call for help from some Loners at the Bus stop who are under attack from the Military. I've completed that part of vanilla game like 10 times and I always used to get this quest.

![defendthepatrolbusstop](https://user-images.githubusercontent.com/35204405/46908360-58c9db00-cf2a-11e8-967b-b83cb2cc90e4.jpg)

However, when playing this scene several times on SRP v1.1.2 and ~August build of SRP v.1.1.3, I've never got this quest. It seemed that these guys got fighting before me even getting close, so when I finally approached them, all the loners were already dead.

**Comment by SurDno** [comment]
UPD: In ModDB discussions I found olegj5 already pointing it (at least the problem is not only on my end), and you responding to him:

> The shootout between the military and stalkers at the Cordon Bus Stop is not rigidly scripted. Sometimes you get the call for help, sometimes not. This is also true of vanilla, although I am unsure whether the SRP somehow reduces the probability of getting the call even further over vanilla. I'll look into it.

I've never met this issue in vanilla and it happened to me three times in a row only in SRP, so I guess SRP 100% reduces the probability of this quest starting or somehow manages to put both sides fighting before Scar can get the call.

**Comment by Decane** [comment]
>I guess SRP 100% reduces the probability of this quest starting or somehow manages to put both sides fighting before Scar can get the call.

Not 100% - I just played through this sequence multiple times with the SRP and sometimes I got the task, other times the stalkers and military started skirmishing as soon my coming within switch distance of them brought them online. It's not yet clear to me why they sometimes start fighting immediately.

I did test making the stalker squad invulnerable to see if them getting shot was the thing that pokes them into combat mode, but that made no difference.

**Comment by SurDno** [comment]
By „100% reduces” I meant „surely reduces“, not „reduces by 100%“. :)
Thanks for describing.

**Comment by Decane** [comment]
I played through this part again and got the task 100% of the time if I loaded a savegame made before talking to Sidorovich for the first time. If I loaded a save made after talking to Sid and hence after the skirmishing squads had already been created, I didn't get the task. So the issue seems related to the state into which the two squads spawn _after_ a game load.

**Comment by Decane** [comment]
e0fc737 prevents premature combat at the bus stop.

Note: It's still possible to miss the task if the player immediately retreats to the opposite direction upon getting within switch distance of the two squads and hence falls outside of the 150x150 meter defend task reception radius when the game evaluates whether to task the player. The task will also not be assigned if the player already has an active defend task.

Both of these are by design and I have no intention of hacking around either of them. If GSC was keen for this task to always be assigned, they would/should have hard-coded this instead of relying on emergent behavior. I'm going to assume that since they didn't, they didn't care whether the task is always assigned or not. I choose to do the same.
