### ISSUE TITLE
Clearing flea market quest has wrong type

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#26]
As soon as you kill the smuggler and other loners during Yoga's second quest, he sends you to clear the flea market.

> They’ve all copped it then? Great job! You can pick up your reward from Tooth. By the way, you’re moving up the ranks. I’m putting you in charge of five of my boys and I already got your lot. I want the diggers to forget even thinking about armed resistance, so I need you and your boys to show them who’s boss. Your target is the flea market. Once you’re done with the diggers, **make sure our boys secure the area and don’t let anyone in**. Your team is already in position, but they won’t do shit without your command.

That makes it a '**Capture**' task (or at least should make it so). However, the quest gets completed as soon as everyone is killed and there's no matter if '_our boys_' really capture the point, so I assume it's '**Eliminate the camp**' type by default.

**Comment by Decane** [comment]
I intentionally made this an 'eliminate' task because if left as a 'capture' task (as in vanilla) and the bandit squad accompanying the player is wiped out, the task becomes impossible to complete - at least until another bandit squad takes their place, which may never happen.

... Unless I script it so another bandit squad targeting the Flea Market always spawns somewhere nearby in the event that the first/current one dies. Let me think about it.

**Comment by SurDno** [comment]
I dunno. For me, a new squad headed off to the flea market as soon as the old one got wiped out.

**Comment by SurDno** [comment]
Task bug?

**Comment by Decane** [comment]
Fixed in https://github.com/Decane/SRP/commit/b7c4bc614a9e73bca3f9916ffb00d0a62f0f53ec.

The bandit allies now respawn at either the "Fortification area" or "Backwoods camp" depending on player location.
