### ISSUE TITLE
'Help' quests get cancelled sometimes with no obvious reason

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#4]

**Comment by Decane** [comment]
Can you describe the problem in a bit more detail? CS has 2 types of defense task - one is a 'help' task where the enemy is already 'at the gates' when the task is received, and the player has 5 game-minutes to get to the target camp before the enemy opens fire. The other is a 'defend the camp' task where a count-down starts as soon as the player receives the task, and when it reaches zero, the enemy departs to attack the target camp.

Which of these 2 did you encounter the issue with? And did you one-shot kill the mutants before they reached their target? I can envision the bug that caused #3 also causing this issue in the event of one-shot kills. And now that that's fixed, I'm left wondering whether this is, too. Do you have a savegame from which to reproduce this?

**Comment by Decane** [comment]
I'm speculatively labeling this one a duplicate of #3 because my fix for that also fixes another, closely related bug that I believe may have been responsible for the issue you have described here, provided that the mutants you killed were one-shot kills. (You insist they weren't, but I can't see any other way the described issue could have happened.)

In #3, I noticed that in both of your savegames, the death callback from the killed creature's object binder systematically fired before the hit callback. And this 'client entity' death callback is set to deactivate the hit callback. Hence, in your saves, the client entity's hit callback was blocked from firing on the entity's death. And before my fix, the only code path that would have credited the player with contributing to a 'capture', 'eliminate', 'help', or 'defend the camp' task was through the client entity's hit callback.

With commit 1924610 however, there are now 2 paths through the code that credit the player with contributing to an active random faction war task - one through the client entity's hit callback (as before), and the other through the server entity's death callback. Usually, both will fire on the creature's death. But even where the client entity's death callback fires before its hit callback—as in your saves—and hence blocks the hit callback from firing at all, the server entity's death callback should still fire, yielding the desired result.

**Comment by SurDno** [comment]
That's one of my proudest _I told you so_'es in past few years. I said that were not one-shot kills!

I've managed to reproduce this bug after six months with October branch of SRP 1.13. [Here's the save!](https://yadi.sk/d/Fg6urevSGO4mkQ)

As far as I remeber, in April I got this bug when some Fleshes were attacking Encampment near Bridge at Escape. I got to the point being attacked and then killed them from distance, using something like AK or MP5, so I assume I could not kill them from just one shot.

This time, I got a 'Help' task on protecting Freedom squad at Barricades from some boars. I did not rush to my faction squad, instead, I rushed to boars and killed them before they got near freedomers. The quest counted as completed (so not getting to the point being attacked is not the matter of this bug).

After that, I almost immediately got a new 'Help' task on protecting the same Freedom squad, but this time that were blind dogs. Again, I did not go to Barricades and killed all of those dogs when they were going near Depot. This time, the quest got cancelled, just like it did in April.

I'm reopening this issue and ask you to remove the duplicate label, since this bug has not been fixed by 1924610.

**Comment by SurDno** [comment]
@Decane, remove the duplicate label, please.

**Comment by Decane** [comment]
@SurDno I can't reproduce the issue you're describing from that savegame - each time I kill the dogs, I get "Task complete". I've tried killing them with the G36 (multi-shot kills) and the SPAS-12 (one-shot kills). I've reloaded about 8 times now. Do you consistently get "Task cancelled" when you kill the dogs after reloading? If so, there might be a race condition in the scripts that plays out one way on your hardware and another way on mine.

**Comment by SurDno** [comment]
I am pretty sure you got this figured out with the last commit.

**Comment by Decane** [comment]
Fixed in https://github.com/Decane/SRP/commit/3243acf52360d354b8ed35dd37cc4b14c8d87c9d.
