### ISSUE TITLE
The bodies of some stalkers do not appear on the mini map.

### ISSUE THREAD

**Issue by JIuBeP** [Decane/SRP#42]
Known bug. The bodies of some stalkers do not appear on the mini map. I remember that only shocker mod 1.9, it was fixed, but I don't know how... can you look?

**Comment by Decane** [comment]
Is there a non-executable installer for Shoker 1.9 anywhere? I'm not brave enough to double-click the .exe installer I keep running into with Google.

**Comment by JIuBeP** [comment]
Decane, Sorry, as far as I remember it is only in this installation format... it's like an original installer from the author. Still, I think it's safe.

**Comment by Decane** [comment]
Fixed in 11230d1, thanks to Shoker.

**Comment by Decane** [comment]
With the hack in 503f825, if you kill an NPC while they are nearby, their corpse dot consistently appears on the minimap, but when you move far away from them and then come back, it'll be gone.

On the other hand, if you kill the NPC when they are far away from you, their corpse dot will consistently appear on the minimap when you get in range of them.

Re-opening due to the first observation.

**Comment by Decane** [comment]
- Introducing a 3-second delay before the corpse dot is added to the minimap makes no difference to the behavior observed in my previous post.

- Furthermore, I believe I have now eliminated the possibility that any scripts are removing the corpse dot when the player goes out of range of it (i.e. far enough from it that it falls outside of the minimap).

- Finally, saving/reloading near the corpse dot seems to disable its disappearing when the player goes out of range of it **in the loaded savegame**.

All of this suggests that the engine 'marks' nearby killed NPCs to have their map spot removed when the player goes out of range of them, but that this 'mark' does not persist across game sessions.

A potential work-around would be to augment Shoker's hack as follows: whenever the player comes within range of a corpse, check if it has a map spot and, if it doesn't, add one. (Don't do this check more than once since no further 'marking' by the engine seems to be done when the player gets in range of an NPC if the NPC is already dead. This is suggested by the observation that NPCs killed by a far-away player don't disappear even if the player subsequently gets in range of them, then goes out of range, and finally comes back in range again.)

**Comment by Decane** [comment]
Fixed in commit 7ec96d6.

**Note:** Saving/reloading may be required for some perma-corpse minimap spots to be displayed.
