### ISSUE TITLE
Weather may sometimes change on loading the same save

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#50]
I know it's probably a well-know bug, but is there really no way to at least workaround it? Like, I don't know, putting current weather in some variable during saving and then forcing the game to load this weather during loading?

_P.S. If this was fixed in SRP, sorry, I do use Atmosfear 1.3 in my saves, but I believe I have properly merged all (one) overlapping files._

**Comment by Marek33** [comment]
I don't think it has been fixed, since with the Moddb version 1.1.2 I still have that bug.

**Comment by Decane** [comment]
This will be difficult to fix completely because the game provides no way to save/load weather transition progress. If the player saves during a weather transition (very common), the best we can do is save the 'pure' weather type that most closely approximates the transitional weather the player saw when saving.

Now suppose the weather transition was clear -> thunder and the player saved exactly mid-way through the transition. Neither 'clear' nor 'thunder' will be a very good approximation for the weather prevailing when the save was made, since the 50/50 hybrid of these is fairly dissimilar to the 'pure' forms of both.

That said, it looks fairly trivial to fix the weather changing between loads of the same save, so that should be an easy win at least.

**Comment by Decane** [comment]
[Here](https://github.com/Decane/SRP/blob/18fb6c0b49528b7c9a57488df701718748f72494/gamedata/scripts/level_weathers.script) is an initial attempt at a fix. Seems to work, but suffers from the caveat about approximating transitional weather, which was explained in https://github.com/Decane/SRP/issues/50#issuecomment-871019101.

**Comment by Decane** [comment]
Fixed in https://github.com/Decane/SRP/commit/5b1a3b4e4091b9939cb7255c7e62dba6e73d4159, still with the caveat that loaded transitional weather will only be approximated. I see no way around that without engine changes.

**Comment by Decane** [comment]
Fixed in https://github.com/Decane/SRP/commit/0a7f5db00c3e1e21b2ce1b70b1afb2b8834419b8, still with the caveat that loaded transitional weather will only be approximated. I see no way around that without engine changes.
