### ISSUE TITLE
Duty Base mess

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#57]
Duty Base sublocations are in a mess both in Vanilla and in SRP. The red circle is considered to be the **Duty Base**, while the green one is the **Eastern Entrance**. I am sure that it's ridiculous and they should obviously be swapped.

![image](https://user-images.githubusercontent.com/35204405/48680142-53a32000-eba9-11e8-8c6e-66aaacd38f3c.png)

**Comment by Decane** [comment]
The green circle indeed designates what the game considers the "Eastern Entrance". However, the center point of the "Duty Base" is actually approximately where the 2nd-left-most squad leader icon is in your screenshot - so to the left of the green circle.

To make matters more confusing, the two right-most squads in your screenshot are in the "Duty Base", not the "Eastern Entrance". And the little guard shack intersected by the bottom portion of the red circle (where a guide is often stationed) is also a part of what the game considers the "Duty Base".

Just reversing the names would mean Freedom squads vying to capture the Duty base would show as headed towards the "Eastern Entrance" instead. And faction war objectives in the PDA would also reference "Eastern Entrance" instead of "Duty Base". I don't think we want that.

Of course, this can be avoided if I change the Freedom faction war target to agr_smart_terrain_1_6_near_2 (currently, "Eastern Entrance") _and_ swap the names around. However, this could negatively affect the Freedom faction war since the squad capacity of agr_smart_terrain_1_6_near_2 is only 2, whereas agr_smart_terrain_1_6 (currently, "Duty Base") has 5. So switching the faction war target would make Freedom send substantially fewer squads towards the Duty base, potentially making the Freedom faction war more frustrating.

I think that might be too high a price to pay for what is otherwise essentially a cosmetic change.

**Comment by SurDno** [comment]
Also, apparently agr_smart_terrain_1_6_near_2 is 'base' (and handles respawn) while agr_smart_terrain_1_6 is 'resource' and does not handle respawn. I just wonder how all of that could have happened.

**Comment by SurDno** [comment]
I manually checked all the waypoints and apparently all the points outside of the institute campus are considered a part of Duty Base, while points inside the institute are considered a part of Eastern Entrance.

I know you closed the issue long ago, but have you considered not swapping but changing the names? This was done by GSC in patch 1.5.03:
![image](https://user-images.githubusercontent.com/35204405/87557056-1fef0500-c6c0-11ea-9cca-662f0e7480e3.png)
