### ISSUE TITLE
NPCs might get stuck in idle state instead of capturing the point

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#64]
They just seem to stand still. If save/load, then they take a few steps and stay still again. I've got this fixed only by injuring one of them and then they took the waypoints they needed to take.

![image](https://user-images.githubusercontent.com/35204405/48680692-9a474900-ebae-11e8-9323-406e38ccd605.png)

[Savefile](https://yadi.sk/d/vJbLSUFEWBx1Ag). [Modified faction_bandit.ltx](https://yadi.sk/d/rLFGeQHWzMFkgA).

**Comment by Decane** [comment]
Also witnessed at the Factory Lobby in the Dark Valley and the Hideout in Hollow at the Garbage. Affects online squads only.

**Comment by Decane** [comment]
Now also witnessed at the Armored Post at the Military Warehouses: a Monolith squad got stuck in front of the truck at the camp. Worryingly -- and unlike in previous similar cases -- my frame-rate tanked the moment this happened.

The squad started moving again and my frame-rate returned to normal once I sniped one of them.

**Comment by Decane** [comment]
The active logic section of squads that get stuck in the Duty base building is [agr_smart_terrain_1_6_to_agr_smart_terrain_1_6_near_2_patrol_1_walk]. They never 'settle into' the building because for `sim_attack_point:is_finished()` to return `true`, a squad must be in the "idle" or "defence" stage, whereas squads that enter the building never seem to leave the "move" stage.

In general, whenever an online "move" stage squad reaches their destination, the following logic in gulag_general.script is supposed to trigger their transition to the "idle" stage, hence permitting `sim_attack_point:is_finished()` to return `true` and making the squad 'settle into' the smart terrain:
```
on_signal = arrive_to_wait|%=request_current_squad_stage(prepare)%
```
Clearly, the signal isn't firing. Why not? A reasonable blind guess might be that none of the way-points for section [agr_smart_terrain_1_6_to_agr_smart_terrain_1_6_near_2_patrol_1_walk] have the "arrive_to_wait" signal defined.

But if we peek into way_l06_agroprom.ltx, we can see that's not the case:
```
p1:name = name01|sig=arrive_to_wait
```
... is defined under [agr_smart_terrain_1_6_to_agr_smart_terrain_1_6_near_2_patrol_1_walk].

Interestingly, the coordinates of way-point p1 are right in front of the building. And for NPCs to even reach the final way-point node (p18) on the top floor where they eventually stop (pictured in SurDno's screenshot), they must walk through p1, since the only path that leads to p18 is through p1. So, why doesn't the signal fire?

Hell if I know, but an easy fix is to move the signal to p18 instead of p1, although this is slightly at odds with what GSC appears to have intended; recall that the coordinates for p1 are right in front of the building, which implies that GSC intended the building to count as 'captured' as soon as an NPC walks into p1, rather than requiring that the NPC reaches the top floor of the building (p18). Eh, I can think of worse compromises.

**Comment by Decane** [comment]
Apparently, `move_mgr:waypoint_callback()` only gets called for [agr_smart_terrain_1_6_to_agr_smart_terrain_1_6_near_2_patrol_1_walk] way-points p6 - p18, which 'explains' why signal "arrive_to_wait" doesn't fire when a squad reaches  way-point p1.

But I don't understand why the callback doesn't fire for all the nodes on the path; `move_mgr:initialize()`, which gets called by `motivator_binder:reinit()`, is what binds the callback:
```
self.object:set_callback(callback.patrol_path_in_point, self.waypoint_callback, self)
```
And this happens very early on, before the NPC even spawns. Either there's something wrong with the callback, or the NPCs aren't navigating through way-points p0 - p5. I'm leaning towards the latter, because when I defined `a=sneak_run` for p1, none of the squad NPCs changed movement style, whereas when I did the same for p6, they did.

Very strange.

**Comment by Decane** [comment]
Should be fixed by https://github.com/Decane/SRP/commit/edb1d83d26b2776dde93b619f6a2290a1c1494ba for every smart terrain.

The fix (or work-around, really): a "path_end" signal is sent to an NPC's active AI scheme when the NPC reaches the terminal way-point of a path, and that signal triggers a transition to the "idle" squad stage if the NPC's squad was in the "move" stage.

I don't know if the waypoint callback always triggers for the terminal way-point without a save/reload, however; I still don't understand why `move_mgr:waypoint_callback()` doesn't get called for every way-point on path "agr_smart_terrain_1_6_to_agr_smart_terrain_1_6_near_2_patrol_1_walk", per https://github.com/Decane/SRP/issues/64#issuecomment-568457720.
