### ISSUE TITLE
Level changer squad behaviour is not identical to vanilla

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#70]
In vanilla, all of these points usually have two squads and one of them could give you a quest on capturing the level_changer point on another location. In the SRP, however, some of these points may have two squads from the start of the game, but then all of them always seem to have just one squad and no more. 

I am talking specifically about this points:

![image](https://user-images.githubusercontent.com/35204405/48681367-13489f80-ebb3-11e8-998c-f083deb31398.png)

**Comment by Decane** [comment]
Not a bug. The faction war target prioritization in the SRP intentionally differs from vanilla to make the faction wars less frustrating, especially since commit d89a652. One of many ways this can manifest is squads preferring to move out of camps in the SRP that they would have preferred to stay at in vanilla if another squad is already stationed there.

With that said, there is nothing special about level changer camps _per se_ in the game's eyes that exempts them from squad migration even in vanilla, so I suspect there is (also) an element of coincidence in your observation about vanilla vs. SRP behavior in respect of such camps.
