### ISSUE TITLE
Character model reverting to default rookie jacket -- remnants of this problem still remain

### ISSUE THREAD

**Issue by Zoney45** [Decane/SRP#95]
In the changelog it states ""Fixed the player's character model reverting back to the default rookie jacket model upon loading a savegame."

This is mostly true and bravo for fixing it.

However there are still issues with this: 

1) If you're carrying around a second suit in your inventory, then the default jacket shows up on your character/hud after loading.

2) If you pick up a suit from the world (to store in your inventory) then the default jacket IMMEDIATELY shows up on your character model/ hud model.

**Comment by SurDno** [comment]
Half an engine-issue, so not fixable fully. I recall @Xottab-DUTY getting it fixed in his OpenXRay.

**Comment by Decane** [comment]
As SurDno says, it's an engine bug [fixed in OpenXRay](https://github.com/OpenXRay/xray-15/commit/4e570d4eaef710625f738d29bbadf78eb930f710). I attempted a work-around in the SRP some time ago, but that [introduced a regression](https://github.com/Decane/SRP/issues/41). So, now we just have to make do without a fix.

**Comment by Decane** [comment]
In https://github.com/Decane/SRP/commit/545ff2d6bcd6939eeb6ea85e9de676f4d87b7321, I've reintroduced the hack to fix the player's character model reverting to the default rookie jacket model upon picking up a new suit, but modified (courtesy of Artos & Shoker) so that it doesn't suffer from the previous regression of also unequipping artifacts.

Thanks to PYP for brining this revised fix to my attention.
